In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3, 4, 5 ,6, 7, 8, 9]
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
array = np.array(my_list)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
type(array)

numpy.ndarray

In [8]:
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array[0]