In [1]:
import numpy as np

In [7]:
array = np.array([1, 2, 3])
array.dtype

dtype('int64')

In [5]:
array = np.array([1, 2, 3], dtype='float64')
array.dtype

dtype('float64')

In [8]:
array

array([1, 2, 3])

In [12]:
array = np.array([0, 1, 2, 3])
array = array.astype(np.bool_)
array

array([False,  True,  True,  True])

In [13]:
array = np.array([0, 1, 2, 3])
array = array.astype(np.string_)
array

array([b'0', b'1', b'2', b'3'], dtype='|S21')

In [14]:
array = np.array(['0', '1', '2', '3'])
array = array.astype(np.int8)
array

array([0, 1, 2, 3], dtype=int8)

In [17]:
array = np.array([0, 1, 2, 3])
array = array.astype(np.longlong)
array

array([0, 1, 2, 3], dtype=int64)