In [1]:
import numpy as np

In [3]:
scalar = np.array(45)
print(scalar)
scalar.ndim

45


0

In [4]:
vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1

In [6]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
]
)
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [10]:
tensor = np.array([[
    [1, 4, 2],
    [2, 3, 3],
    [23, 2, 5],
    [5, 45, 7],
],
[
    [1, 4, 2],
    [2, 3, 3],
    [23, 2, 5],
    [5, 45, 7],
]])
print(tensor)
tensor.ndim

[[[ 1  4  2]
  [ 2  3  3]
  [23  2  5]
  [ 5 45  7]]

 [[ 1  4  2]
  [ 2  3  3]
  [23  2  5]
  [ 5 45  7]]]


3

## Added or deleted dimensions 

In [11]:
vector = np.array([1, 2, 3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [13]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [14]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
