In [1]:
import numpy as np

In [2]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones((10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand()

0.6311800663428875

In [15]:
np.random.rand(4)


array([0.80235051, 0.18075234, 0.42190298, 0.71013488])

In [16]:
np.random.rand(4, 4)

array([[0.95691238, 0.80475287, 0.88434416, 0.27662615],
       [0.43358563, 0.00772433, 0.1474629 , 0.97747773],
       [0.17057313, 0.175879  , 0.0312845 , 0.52385189],
       [0.60940709, 0.14122746, 0.7505969 , 0.24726521]])

In [17]:
np.random.randint(1, 15)

14

In [18]:
np.random.randint(1, 100, (10, 10))

array([[98, 82, 15, 53, 71, 48, 78, 50, 37, 59],
       [70, 77, 76,  4, 35, 49, 57, 95, 95, 70],
       [58, 95,  3, 22, 49, 40,  8, 18, 12,  9],
       [21, 64, 27, 38, 75, 85, 97, 37, 15, 15],
       [30, 75, 87, 98, 28, 55, 53, 68, 31, 61],
       [35, 78, 11,  1, 13, 16, 16, 86, 52, 55],
       [46, 70,  5,  1, 70, 27, 24, 98, 59, 18],
       [ 2, 46, 44, 30, 15,  6, 21, 40, 59, 86],
       [81, 45, 87, 81,  3, 71, 36, 88, 20, 78],
       [70,  6, 73, 39, 66, 47, 56,  4, 26, 12]])