In [1]:
import numpy as np

In [4]:
array = np.random.randint(1, 10, (3, 2))

In [6]:
array

array([[7, 2],
       [4, 6],
       [7, 4]])

In [11]:
array.reshape(2, 3)

array([[7, 2, 4],
       [6, 7, 4]])

In [10]:
array.reshape(1, 6)

array([[7, 2, 4, 6, 7, 4]])

In [12]:
np.reshape(array, (1, 6))

array([[7, 2, 4, 6, 7, 4]])

In [18]:
array

array([[7, 2],
       [4, 6],
       [7, 4]])

In [16]:
np.reshape(array, (2, 3), 'C')

array([[7, 2, 4],
       [6, 7, 4]])

In [19]:
np.reshape(array, (2, 3), 'F')

array([[7, 7, 6],
       [4, 2, 4]])

In [20]:
np.reshape(array, (2, 3), 'A')

array([[7, 2, 4],
       [6, 7, 4]])