In [2]:
import numpy as np

In [26]:
array = np.random.randint(1, 20, 10)
array

array([18,  3,  8, 10, 14, 16,  9, 14, 12, 15])

In [28]:
matriz = array.reshape(2, 5)
matriz

array([[18,  3,  8, 10, 14],
       [16,  9, 14, 12, 15]])

In [11]:
array.max()

14

matrix.max(eje)

si eje == 0 es el eje y
si eje == 1 es el eje x

In [14]:
matriz.max(0)

array([13, 11, 11, 14, 10])

In [15]:
array.argmax()

8

In [18]:
matriz.argmax(0)

array([0, 1, 0, 1, 1])

In [19]:
array.min()

7

In [20]:
matriz.min(0)

array([ 7,  8, 10, 12,  7])

In [21]:
matriz.min(1)

array([7, 7])

In [22]:
matriz.argmin(0)

array([1, 0, 1, 0, 0])

In [23]:
matriz.argmin(1)

array([4, 0])

In [27]:
array.ptp()

15

In [29]:
matriz.ptp(0)

array([2, 6, 6, 2, 1])

In [31]:
np.percentile(array, 50)

13.0

In [34]:
array.sort()

In [35]:
np.median(array)

13.0

In [37]:
np.median(matriz, 1)

array([ 9., 15.])

In [38]:
np.std(array)

4.2296571965113205

In [39]:
np.var(array)

17.890000000000004

In [40]:
np.std(array) ** 2

17.890000000000004

In [41]:
np.mean(array)

11.9

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([4, 6])


In [4]:
np.concatenate((a, b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [6]:
a.ndim
b.ndim

1

In [10]:
b = np.expand_dims(b, axis=0)
b

array([[[[4, 6]]]])

In [8]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [4, 6]])