In [1]:
import numpy as np

In [4]:
arr = np.linspace(1, 10, 10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [6]:
index_condition = arr > 5
index_condition

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [11]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [12]:
arr[arr > 5] = 99

In [13]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [14]:
arr[arr == 99]

array([99, 99, 99, 99, 99], dtype=int8)