In [1]:
import numpy as np

In [2]:
my_list = [1, 2]
my_list

[1, 2]

In [6]:
for i in range(0, len(my_list)-1):
    my_list[i] *= 2

my_list

[2, 4]

In [9]:
arr = np.arange(0, 10)
arr_2 = arr.copy()

# Operators

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
1 / arr

/tmp/ipykernel_115519/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
arr + arr_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
arr * arr_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [18]:
arr / arr_2

/tmp/ipykernel_115519/963544532.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr_2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [19]:
arr // arr_2

/tmp/ipykernel_115519/1805083175.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  arr // arr_2


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
arr ** arr_2

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [22]:
arr & arr_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
matriz = arr.reshape(2, 5)
matriz_2 = matriz.copy()

In [26]:
matriz + matriz_2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [30]:
matriz - matriz_2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
np.matmul(matriz, matriz_2.T)

array([[ 30,  80],
       [ 80, 255]])

In [33]:
matriz @ matriz_2.T

array([[ 30,  80],
       [ 80, 255]])